package(default_visibility = ["//visibility:public"])

cc_test(
  name = "token_test",
  srcs = ["token_test.cc"],
  deps = [
       "//src:token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "keywordtoken_test",
  srcs = ["keywordtoken_test.cc"],
  size = "small",
  deps = [
       "//src:keywordtoken",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "punctoken_test",
  srcs = ["punctoken_test.cc"],
  size = "small",
  deps = [
       "//src:punctoken",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "reloptoken_test",
  srcs = ["reloptoken_test.cc"],
  size = "small",
  deps = [
       "//src:reloptoken",
       "//third_party/gtest:gtest_main",
  ],
)