cc_test(
  name = "parser_test",
  srcs = ["parser_test.cc"],
  size = "small",
  deps = [
       "//src:parser",
       "//third_party/gtest:gtest_main",
       "//util:ptr_util",
  ],
)

cc_test(
  name = "semantic_analyzer_test",
  srcs = ["semantic_analyzer_test.cc"],
  size = "small",
  deps = [
       "//src:parser",
       "//third_party/gtest:gtest_main",
       "//util:ptr_util",
  ],
)